#!/usr/bin/env bash

apply_layout() {
	mapfile -t active_monitors < <(xrandr | grep " connected" | cut -d" " -f1)
	mapfile -t inactive_monitors < <(xrandr | grep " disconnected" | cut -d" " -f1)

	local count=${#active_monitors[@]}
	local primary=${active_monitors[0]}

	if [[ ${count} -eq 0 ]]; then
		echo "No active monitors detected."
		echo "How are you even running this script, bruh?"
		exit 1
	fi

	echo "${count} active monitor(s) detected. Setting up layout..."

	xrandr --output "${primary}" --auto &>/dev/null

	case ${1} in
		"duplicate")
			for monitor in "${active_monitors[@]}"; do
				xrandr --output "${monitor}" --auto --same-as "${primary}" &>/dev/null
			done

			echo "All monitors duplicated to ${primary}"
			;;
		"extend")
			for i in "${!active_monitors[@]}"; do
				if [[ ${i} -eq 0 ]]; then
					continue
				fi

				side="right-of"
				if [[ ${i} -eq 1 && ${count} -eq 3 ]]; then 
					side="left-of"
				fi
				xrandr --output "${active_monitors[$i]}" --${side} "${primary}" --auto &>/dev/null
			done

			( IFS="|"; echo "Layout set: ${active_monitors[*]}" )
			;;
		"extend-portrait")
			for i in "${!active_monitors[@]}"; do
				if [[ ${i} -eq 0 ]]; then
					continue
				fi

				side="right-of"
				if [[ ${i} -eq 1 && ${count} -eq 3 ]]; then
					side="left-of"
				fi
				xrandr --output "${active_monitors[$i]}" --rotate left --${side} "${primary}" --auto &>/dev/null
			done

			( IFS="|"; echo "Layout set: ${active_monitors[*]}" )
			;;
	esac

	for monitor in "${inactive_monitors[@]}"; do
		xrandr --output "${monitor}" --off &>/dev/null
	done
	exit 0
}

mode="extend"

while [[ ${#} -gt 0 ]]; do
    case ${1} in
        -h|--help)
            cat <<EOF
Usage: monsetor [OPTIONS]

Automatically configures monitor layout based on connected monitors.

Options:
  -h, --help        	Show this help message
  -e, --extend      	Extend primary monitor to all connected monitors (default)
  -d, --duplicate   	Duplicate primary monitor to all connected monitors
  -p, --extend-portrait	Extend primary monitor and set other monitors to portrait mode
EOF
            exit 0
            ;;
        -d|--duplicate)
            mode="duplicate"
            ;;
        -e|--extend)
            mode="extend"
            ;;
		-p|--extend-portrait)
			mode="extend-portrait"
			;;
        *)
            echo "Unknown option: ${1}"
            echo "Use -h or --help for usage information."
            exit 1
            ;;
    esac
    shift
done

apply_layout "${mode}"
